[package]
name = "calphad"
version = "0.1.0"
edition = "2024"

[lib]
name = "calphad"
crate-type = ["cdylib", "rlib"]

[package.metadata.maturin]
name = "majordome.calphad"
bindings = "pyo3"

[dependencies]
pyo3 = "0.27.0"
