[package]
name = "constants"
version = "0.1.0"
edition = "2024"

[lib]
name = "constants"
crate-type = ["cdylib", "rlib"]

[package.metadata.maturin]
name = "majordome.constants"
bindings = "pyo3"

[dependencies]
pyo3 = "0.27.0"
