##############################################################################
# Documentation and help at https://quarto.org/docs/books/
#
# Typical commands to use:
# - quarto preview --no-browser
# - quarto render --to pdf
# - quarto render --to html
##############################################################################

project:
  type: book

execute:
  python: "./.venv/Scripts/pythonw.exe"

##############################################################################
# Structure
##############################################################################

book:
  title: "Notes Book"
  author: "Walter Dal'Maz Silva"
  date: "today"

  chapters:
    - index.qmd

    - part: "Thermodynamics"
      chapters:
      - chap-thermodynamics/converting-shomate.qmd
      - chap-thermodynamics/calphad-nitrides.qmd
      - chap-thermodynamics/minerals-scraper.qmd

  # --------------------------------------------------------------------------
  # MODEL PREDICTIVE CONTROL
  # --------------------------------------------------------------------------

    - part: "Model Predictive Control"
      chapters:
        - chap-controls/mpc-multiple-shooting.qmd
        - chap-controls/mpc-boiling-evaporation.qmd
        - chap-controls/mpc-kinetics-part-a.qmd

  # --------------------------------------------------------------------------
  # FINITE VOLUME METHOD
  # --------------------------------------------------------------------------

    - part: "Finite Volume Method"
      chapters:
        - chap-finite-volumes/index.qmd
        - chap-finite-volumes/diffusion-1d/index.qmd
        - chap-finite-volumes/convection-1d/index.qmd

  # --------------------------------------------------------------------------
  # ANSYS FLUENT
  # --------------------------------------------------------------------------

    - part: "Ansys Fluent"
      chapters:
        - chap-ansys-fluent/tui-basics.qmd
        - chap-ansys-fluent/tui-config.qmd
        - chap-ansys-fluent/tui-setup.qmd
        - chap-ansys-fluent/tui-solution.qmd
        - chap-ansys-fluent/tui-results.qmd

  # --------------------------------------------------------------------------
  # ELMER CSC
  # --------------------------------------------------------------------------

    - part: "Elmer CSC"
      chapters:
        - chap-elmer-csc/intro.qmd
        - chap-elmer-csc/elmer.qmd
        - chap-elmer-csc/sif.qmd
        - chap-elmer-csc/matc.qmd

  # --------------------------------------------------------------------------
  # ELMER CASES
  # --------------------------------------------------------------------------

    # - part: "Elmer Cases"
    #   chapters:
    #     - chap-elmer-cases/conduction-1/README
    #     - chap-elmer-cases/conduction-2/README
    #     - chap-elmer-cases/conduction-3/README
    #     - chap-elmer-cases/thermomechanical-1/README

  # --------------------------------------------------------------------------
  # SCIENTIFIC COMPUTING
  # --------------------------------------------------------------------------

    - part: "Scientific Computing"
      chapters:
        - chap-computing/introduction.qmd
        - chap-computing/operating-systems.qmd
        - chap-computing/tools-selection.qmd
        - chap-computing/tools-portable.qmd

  # --------------------------------------------------------------------------
  # SCIENTIFIC PROGRAMMING
  # --------------------------------------------------------------------------

    - part: "Scientific Programming"
      chapters:
        - chap-programming/rust.qmd
        - chap-programming/haskell.qmd

  # --------------------------------------------------------------------------
  # IMAGE ANALYSIS
  # --------------------------------------------------------------------------

    - part: "Image Analysis"
      chapters:
        - chap-image-analysis/porosity-measurement.qmd
        - chap-image-analysis/metadata-extraction.qmd

  # --------------------------------------------------------------------------
  # REFERENCES
  # --------------------------------------------------------------------------

    - references.qmd

bibliography: ../notes/references.bib

##############################################################################
# Formatting
##############################################################################

format:
  html:
    highlight-style: github
    # highlight-style: pygments
    theme:
      - sandstone
      # - superhero

  pdf:
    highlight-style: github
    documentclass: scrreprt
    papersize: a4
    mainfont: "Latin Modern Sans"
    sansfont: "Latin Modern Sans"
    geometry:
      - margin=20mm

##############################################################################
# EOF
##############################################################################