[package]
name = "diffusion"
version = "0.1.0"
edition = "2024"

[lib]
name = "diffusion"
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "majordome.diffusion"
bindings = "pyo3"

[dependencies]
pyo3 = "0.27.0"
constants = { path = "../constants" }
